-- Pricr migration 0007 — run in the Supabase SQL editor.
-- Billing / partner-code support. The app keeps the full billing state in businesses.config (jsonb);
-- these relational columns mirror the key fields so the proxy + Stripe webhook can query/update them
-- efficiently with the service role. All statements are idempotent (IF NOT EXISTS) — safe to re-run.

-- ── Subscription + partner mirror on businesses ───────────────────────────────
alter table businesses add column if not exists subscription_status text default 'trial';
alter table businesses add column if not exists partner_code        text;
alter table businesses add column if not exists trial_started_at     timestamptz default now();
alter table businesses add column if not exists stripe_customer_id   text;

create index if not exists businesses_subscription_status_idx on businesses (subscription_status);
create index if not exists businesses_partner_code_idx        on businesses (partner_code);

-- ── Veraa partner codes ────────────────────────────────────────────────────────
-- Generated by the super-admin dashboard (master-token gated, via the proxy service role).
create table if not exists veraa_codes (
  code        text primary key,
  client_name text,
  created_at  timestamptz default now(),
  used_by     text,         -- the business code that redeemed it
  used_at     timestamptz,
  revoked     boolean default false
);

-- RLS: the table is only ever read/written by the proxy using the service role (which bypasses RLS),
-- so enable RLS with NO anon/authenticated policies — the app never touches it directly.
alter table veraa_codes enable row level security;
